[project]
name = "open-finance-api"
version = "0.1.0"
description = "The API for an finance control system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.12",
    "ruff>=0.12.0",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.3",
]